# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee74ba12a768844a662cc82a204d971d2324c659570d4bfd15c4d82c77e02c9eae9d8792728551c17b1929ef9a2dc0dabbf50a9dcba8e1d06e609fb0380553f

test:
  secret_key_base: 299ca1b953d26461cbe881299ea8e3d8278f970d8b0e5bfd5cb6d9b93bb63246c11927e3de36465e2e66129b866078e46be9b57498364db2efceb3f2478f66de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
